import React, { useState, useEffect } from 'react';
import axios from 'axios';

const TestComponent=()=>{
    const [ systime, setSystime ] = useState('curr-systime');
    const [ updateResult, setUpdateResult ] = useState("");

    // useEffect (()=>{ axios.get('/testee/read/{id}').then(( response )=>{ setSystime( response.data.data ) }) });

    const testWrapperStyle= { margin: '20px', padding: '20px', border: '1px solid white', width: 'fit-content', fontSize: '1.2rem', textAlign: 'center' };
    // const create=()=>{
    // // const data = { testTitle: "TITLE GENERATED BY REACT-PRESENTATION",testDescription: "DESCRIPTION GENERATED BY REACT-PRESENTATION" };
    //     axios({
    //         method: 'GET',
    //         url: 'https://localhost:3000/testee/read/1', data
    //     }).then((data)=>{ setUpdateResult(data.data.data) });
    // }

    const createTest=()=>{
        const data = { testTitle: "TITLE GENERATED BY REACT-PRESENTATION",testDescription: "DESCRIPTION GENERATED BY REACT-PRESENTATION" };
        axios.post('https://localhost:3000/testee/read/1', data).then((response)=>{
            setUpdateResult(response.data);
            console.log(response.data);
        })
    }

    return(
        <div style={ testWrapperStyle }>
            <h2>test</h2>
            {/*<p>{ systime }</p>*/}
            <p>{ updateResult }</p>
        </div>
    );
}
export default TestComponent;