server:
  port: 3000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        grobally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: validate
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    generate-ddl: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jwt:
    secret: jwtsecret
  logging.level:
    org.hibernate.SQL: debug
  cors:
    allowedOrigins: '*'
  app:
    jwtSecret: secret
    jwtExpirationInMs: 360000