server:
  port: 3000

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        globally_quoted_identifiers: true
        ddl-auto: none
#        dialect: org.hibernate.dialect.MariaDB103Dialect
        generate-ddl: create
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;MODE=MYSQL
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Asia/Seoul
#  sql:
#    init:
#      schema-locations: classpath:/database/schema.sql
#      data-locations: classpath:/database/data.sql
#      mode: always
#      continue-on-error: true
logging:
  level:
    org.hibernate.SQL: debug
app:
  jwtSecret: jwtSecretKey
  jwtExpirationInMs: 360000
