server:
  port: 3000
spring:
  profiles:
    datasource:
      url: jdbc:mariadb://localhost:3306
      driver-class-name: org.mariadb.jdbc.Driver
      username: codepark
      password: diffos132Qa
  h2:
    console:
      enabled: true
      path: /test_db
  datasource:
    #        driver-class-name: org.h2.Driver
    #        url: jdbc:h2:mem:testdb
    #        username: sa
    #        password:
  data:
    maria:
      jdbc-url: jdbc:mariadb://nlm-maridb.cygvvsgvg5ai.us-east-2.rds.amazonaws.com:3306/codepark?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: codepark
      password: diffos132Qa
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: create
        dialect: org.hibernate.dialect.MariaDB53Dialect
    show-sql: true
    generate-ddl: true
jwt:
  secret: jwtsecret
logging.level:
  org.hibernate.SQL: debug