server:
  port: 3000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    generate-ddl: true
jwt:
  secret: jwtsecret
logging.level:
  org.hibernate.SQL: debug